import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Header from "./components/Header"
import Footer from "./components/Footer"
import { headers } from "next/headers"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const headersList = headers()
    const host = (await headersList).get("host") || ""

    // if it is brand-a then its in English with blue theme
    const isBrandA = host?.includes("brand-a")

    return (
        <html lang="en">
            <head>
                <script
                    src="https://kit.fontawesome.com/3540322285.js"
                    crossOrigin="anonymous"
                ></script>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
                dir={isBrandA ? "ltr" : "rtl"}
            >
                <Header isBrandA={isBrandA} />
                {children}
                <Footer isBrandA={isBrandA} />
            </body>
        </html>
    )
}
